### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by briankgarland** [gregcoffman/AzureVMSitecoreDevelopment#1]
The instructions that list the files that need to be uploaded to the blob container show several json files but where do I find these?

**Comment by gregcoffman** [comment]
From the Sitecore [9.1.1 download page](https://dev.sitecore.net/Downloads/Sitecore_Experience_Platform/91/Sitecore_Experience_Platform_91_Update1.aspx), under **Download options for an On Premise deployment**, download the **Packages for XP Single**.  The files are located within the **XP0 Configuration filesXXX.zip**

**Comment by briankgarland** [comment]
Got 'em, thanks!
